"""
Custom MaruLang Application
This file was generated by maru install command.
"""
from maru_lang import MaruLangApp

# Create your custom MaruLang instance
app = MaruLangApp(
    title="My MaruLang App",
    version="1.0.0",
    description="Custom MaruLang Application"
)

# You can customize the app here
# For example:
# - Add custom startup events
# - Add custom routes
# - Add middleware
# - Configure CORS settings

@app.on_event("startup")
async def custom_startup():
    """Custom startup event"""
    print("🚀 Custom MaruLang app started!")

# Optional: Add custom routes
# @app.get("/custom-health")
# async def custom_health_check():
#     return {"status": "healthy", "custom": True}

# The app instance will be imported by the serve command
# Usage: maru serve --app-module main:app